/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;



/**
 *
 * @author saura
 */
public class EditBusDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditBusDetails
     */
        public void infoMessage(String message, String tittle) {
        JOptionPane.showMessageDialog(null, message, tittle, JOptionPane.INFORMATION_MESSAGE);
    }

    String Busname;
    public EditBusDetails(String Text) {
        initComponents();
       
        this.Busname=Text;
                try {
            Class.forName("com.mysql.jdbc.Driver");
            String databaseURL = "jdbc:mysql://localhost:3306/busm";
            Connection con = DriverManager.getConnection(databaseURL, "root", "");
            Statement stat = con.createStatement();    
            String selectQuery = "select * from bus_details where bus_no='"+Busname+"'";
            ResultSet rs=stat.executeQuery(selectQuery);
            while(rs.next()){
             String busno=rs.getString("bus_no");
             String source=rs.getString("bus_source");
             String destination=rs.getString("bus_dest");
             String time=rs.getString("depart_time");
             String price=rs.getString("price");
             String seats=rs.getString("total_seat");
             busnoTF.setText(busno);
             sourceTF.setText(source);
             destinationTF.setText(destination);
             timeTF.setText(time);
             priceTF.setText(price);
             seatsTF.setText(seats);
             java.util.Date date=new java.util.Date();
             departDateDP.setDate(date);
            }
            } catch (Exception e) {
            System.out.println(e);
        }
        SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
        departDateDP.setFormats(format);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sourceTF = new javax.swing.JTextField();
        priceTF = new javax.swing.JTextField();
        destinationTF = new javax.swing.JTextField();
        departDateDP = new org.jdesktop.swingx.JXDatePicker();
        busnoTF = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        timeTF = new javax.swing.JTextField();
        seatsTF = new javax.swing.JTextField();
        moveCB = new javax.swing.JComboBox();
        label1 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Bus No");

        jLabel2.setText("Source");

        jLabel3.setText("Date");

        jLabel4.setText("Price");

        sourceTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sourceTFKeyPressed(evt);
            }
        });

        priceTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceTFKeyPressed(evt);
            }
        });

        destinationTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                destinationTFKeyPressed(evt);
            }
        });

        departDateDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                departDateDPMouseReleased(evt);
            }
        });
        departDateDP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                departDateDPKeyReleased(evt);
            }
        });

        busnoTF.setText("Bus NO");

        jLabel6.setText("Destination");

        jLabel7.setText("Movement");

        jLabel8.setText("Time");

        jLabel9.setText("Seats");

        seatsTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                seatsTFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                seatsTFKeyReleased(evt);
            }
        });

        moveCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UP", "DOWN" }));

        label1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label1.setText("Edit Bus Details");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("*in hh:mm format (24-Hour)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(busnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(32, 32, 32)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(departDateDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sourceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(212, 212, 212)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(moveCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(destinationTF)
                                        .addComponent(timeTF)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(seatsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(140, 140, 140))))
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(busnoTF)
                    .addComponent(jLabel7)
                    .addComponent(moveCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(destinationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(departDateDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seatsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String busnoD=busnoTF.getText();
       String busMoveD=(String)moveCB.getSelectedItem();
       String bussourceD=sourceTF.getText();
       String busdestD=destinationTF.getText();
              java.util.Date departDateD= departDateDP.getDate();
             SimpleDateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
       String departDate = oDateFormat.format(departDateD);
       String departTimeD=timeTF.getText();
       String priceD=priceTF.getText();
       String seatD=seatsTF.getText();
       
       String time = "([01]?[0-9]|2[0-3]):[0-5][0-9]";
        Pattern patt = Pattern.compile(time);
        Matcher regexMatcher = patt.matcher(timeTF.getText());
        
       if(busdestD.isEmpty() || bussourceD.isEmpty() || departTimeD.isEmpty() || priceD.isEmpty() || seatD.isEmpty()){
           JOptionPane.showMessageDialog(this, "Enter valid Details");
       }
       else{
           if(!regexMatcher.matches()){
               JOptionPane.showMessageDialog(this, "Enter correct details!");
           }
           
           else{
        try
        {
        
             Class.forName("com.mysql.jdbc.Driver");
            String databaseURL = "jdbc:mysql://localhost:3306/busm";
            Connection con = DriverManager.getConnection(databaseURL, "root", "");
            Statement stat = con.createStatement();    
            String selectQuery = "select * from bus_details where bus_no='"+busnoD+"'";
            
            ResultSet rs=stat.executeQuery(selectQuery);
          String insertQuery = "update bus_details set movement='"+busMoveD+"',bus_source='"+bussourceD+"',bus_dest='"+busdestD+"',depart_date='"+departDate+"',depart_time='"+departTimeD+"',price='"+priceD+"',total_seat='"+seatD+"' where bus_no='"+Busname+"'";
           
          stat.executeUpdate(insertQuery);
          infoMessage("Bus Details is Updated", "Great work !!");
          dispose();
            
        }
        catch(Exception e)
        {
        }
           }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sourceTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sourceTFKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            sourceTF.setEditable(true);
        }
        else{
            sourceTF.setEditable(false);
        }
    }//GEN-LAST:event_sourceTFKeyPressed

    private void destinationTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_destinationTFKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            destinationTF.setEditable(true);
        }
        else{
            destinationTF.setEditable(false);
        }
    }//GEN-LAST:event_destinationTFKeyPressed

    private void priceTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTFKeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String price = priceTF.getText();
        //int len = price.length();
        if(Character.isLetter(c)){
            priceTF.setEditable(false);
        }
        else{
            priceTF.setEditable(true);
        }
    }//GEN-LAST:event_priceTFKeyPressed

    private void seatsTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seatsTFKeyReleased
       // TODO add your handling code here:
    }//GEN-LAST:event_seatsTFKeyReleased

    private void seatsTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seatsTFKeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String price = priceTF.getText();
        //int len = price.length();
        if(Character.isLetter(c)){
            priceTF.setEditable(false);
        }
        else{
            priceTF.setEditable(true);
        }
    }//GEN-LAST:event_seatsTFKeyPressed

    private void departDateDPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_departDateDPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_departDateDPKeyReleased

    private void departDateDPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departDateDPMouseReleased
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_departDateDPMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel busnoTF;
    private org.jdesktop.swingx.JXDatePicker departDateDP;
    private javax.swing.JTextField destinationTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Label label1;
    private javax.swing.JComboBox moveCB;
    private javax.swing.JTextField priceTF;
    private javax.swing.JTextField seatsTF;
    private javax.swing.JTextField sourceTF;
    private javax.swing.JTextField timeTF;
    // End of variables declaration//GEN-END:variables
}
