/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.management;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author saura
 */
public class EditEmployee extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditEmployee
     */
String EmployeeName;
    public EditEmployee(String Text) {
        initComponents();
        this.EmployeeName=Text;
                try {
            Class.forName("com.mysql.jdbc.Driver");
            String databaseURL = "jdbc:mysql://localhost:3306/busm";
            Connection con = DriverManager.getConnection(databaseURL, "root", "");
            Statement stat = con.createStatement();    
            String selectQuery = "select * from employee_details where firstname='"+EmployeeName+"'";
            ResultSet rs=stat.executeQuery(selectQuery);
            while(rs.next()){
             String firstname=rs.getString("firstname");
             String lastname=rs.getString("lastname");
             String phoneno1=rs.getString("phoneno1");
             String phoneno2=rs.getString("phoneno2");
             firstnameTF.setText(firstname);
             lastnameTF.setText(lastname);
             phoneno1TF.setText(phoneno1);
             phoneno2TF.setText(phoneno2);
            }
            } catch (Exception e) {
            System.out.println(e);
        }
    }
        public void infoMessage(String message, String tittle) {
        JOptionPane.showMessageDialog(null, message, tittle, JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstnameTF = new javax.swing.JLabel();
        lastnameTF = new javax.swing.JLabel();
        phoneno1TF = new javax.swing.JTextField();
        phoneno2TF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Firstname");

        jLabel2.setText("Lastname");

        jLabel3.setText("PhoneNo1");

        jLabel4.setText("PhoneNo2");

        firstnameTF.setText("Firstname");

        lastnameTF.setText("Lastname");

        phoneno1TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneno1TFKeyPressed(evt);
            }
        });

        phoneno2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneno2TFActionPerformed(evt);
            }
        });
        phoneno2TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneno2TFKeyPressed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Edit Employee Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstnameTF)
                            .addComponent(phoneno1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(59, 59, 59)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastnameTF)
                                .addComponent(phoneno2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(120, 120, 120)))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lastnameTF)
                    .addComponent(jLabel1)
                    .addComponent(firstnameTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phoneno1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(phoneno2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String phno1 = phoneno1TF.getText();
        String phno2 = phoneno2TF.getText();
        int len1 = phno1.length();
        int len2 = phno2.length();
        
         if((len1==10) && (len2==10)){
        String phoneno1 = phoneno1TF.getText();
        String phoneno2 = phoneno2TF.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String databaseURL = "jdbc:mysql://localhost:3306/busm";
            Connection con = DriverManager.getConnection(databaseURL, "root", "");
            Statement stat = con.createStatement();    
            String selectQuery = "select * from employee_details where firstname='"+EmployeeName+"'";
            System.out.println(selectQuery);
           ResultSet rs=stat.executeQuery(selectQuery);
           System.out.println(rs.next());
           if(rs.next()==true)
           {
             infoMessage("Phone Number Already Registered", "Update Failed!!");
           }
           else
           {
          String insertQuery = "update employee_details set phoneno1='"+phoneno1+"',phoneno2='"+phoneno2+"' where firstname='"+EmployeeName+"'";
           
          stat.executeUpdate(insertQuery);
           infoMessage("Employee Details Updated", "Successful!!!");
          dispose(); 
           }
          

        } catch (Exception e) {
            System.out.println(e);
        }
        }
        else{
            JOptionPane.showMessageDialog(this, "Enter valid details!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void phoneno2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneno2TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneno2TFActionPerformed

    private void phoneno1TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneno1TFKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String phno = phoneno1TF.getText();
        int len = phno.length();
        if(Character.isLetter(c)){
            phoneno1TF.setEditable(false);
        }
        else{
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
                if(len < 10){
                    phoneno1TF.setEditable(true);
                }
                else{
                    phoneno1TF.setEditable(false);
                }
            }
           else{
                if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                    phoneno1TF.setEditable(true);
                }
                else{
                    phoneno1TF.setEditable(false);
                }
            }
        }
    }//GEN-LAST:event_phoneno1TFKeyPressed

    private void phoneno2TFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneno2TFKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String phno = phoneno2TF.getText();
        int len = phno.length();
        if(Character.isLetter(c)){
            phoneno2TF.setEditable(false);
        }
        else{
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
                if(len < 10){
                    phoneno2TF.setEditable(true);
                }
                else{
                    phoneno2TF.setEditable(false);
                }
            }
           else{
                if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                    phoneno2TF.setEditable(true);
                }
                else{
                    phoneno2TF.setEditable(false);
                }
            }
        }
    }//GEN-LAST:event_phoneno2TFKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstnameTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lastnameTF;
    private javax.swing.JTextField phoneno1TF;
    private javax.swing.JTextField phoneno2TF;
    // End of variables declaration//GEN-END:variables
}
